# Page settings

baseurl = "https://deftnerd.github.io/"
languageCode = "en-us"
title = "Adam Brown CV"
theme = "hugo-orbit-theme"

# Do not build files for websites. Need them? Set to false
disableRSS = false
disableSitemap = false
disable404 = true



[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false



[params]

# Meta
    description = "Adam Brown CV"
    author = "Adam Brown"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-4.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Adam Brown"
        tagline = "Web Developer"
        avatar = "profile.png"
        # qr_code = "qr_code.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//deftnerd.com"
        title = "deftnerd.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/deftnerd/"
        title = "deftnerd"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "https://github.com/deftnerd"
        title = "deftnerd"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+16077934147"
        title = "(607) 793-4147"

    # Education section
    [params.education]
        enable = true
        title = "Certs & Awards"

        [[params.education.list]]
        details = "Certified Bitcoin Professional"
        college = "CryptoCurrency Certification Consortium"
        dates = "Sep 2014 - Sep 2016"

        [[params.education.list]]
        details = "Winner of $250,000 prize"
        college = "Texas Bitcoin Conference"
        dates = "2014"

    # Languages section
    [params.language]
        enable = false
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Sport; Running, swimming, gym. School Swimming team – District freestyle champion, School Athletics team – District cross country champion, Placed 2nd in U16 Spelthorne 4K Road Race, School Basketball team (District champions 1998), Placed 6th in Southern Schools Modern Biathlon Championships 2001, ranked 14th in the UK, Awarded School Physical Education Prize 1998."

        [[params.interests.list]]
        interest = "Education; Tutored GCSE Mathematics privately, I have an interest in education especially combined with technology."

        [[params.interests.list]]
        interest = "Technology; RISC-V, MR/AR/VR; Mixed Reality, Augmented Reality, Virtual Reality. Solidity, Ethereum, GODOT, Elixir/Phoenix, AI; TensorFlow, DeepSpeech. C++, Linux; Gentoo, *BSD, Ruby, Ruby-on-Rails, RSpec, Shell scripting, Ethical hacking, C#, Unity3d, Unreal Engine, USRP/GNU Radio, React.js, jQuery, Metasploit, Wireshark, Kali, Qt, KDE, Python, OpenCV, WebGL, OpenGL, Vulkan, OpenCL, PostgreSQL, Tor, Docker, Git, Git LFS, GitLab, Puppet, Premiere Pro."

        [[params.interests.list]]
        interest = "Art; Blender, Maya, 3ds Max, V-Ray, Wacom Bamboo, Krita, Illustrator, Photoshop."

        [[params.interests.list]]
        interest = "Music; Guitar, Ocarina, Keyboard."

        [[params.interests.list]]
        interest = "Physics; Quantum Mechanics, Particle Physics, Thermonuclear Fusion (stable fusion reactions as a future energy source), Software-defined radio: GNU Radio, LimeSDR Mini."

        [[params.interests.list]]
        interest = "Videography; Filming and editing footage taken with the Panasonic GH5 and merging with audio recorded with the Zoom H4n."

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """
          A leader with a strong background in building remote teams, coaching, guiding performance, and monitoring development. Excels at independently designing and building amazing products and services. Strong believer in innovation and constant learning.

          Can develop the full-stack, from programming, database design and maintenance, to server management and operations. Over 20 years experience in the IT and Cloud platforms/DevOps. Over 10 years experience in professional software development and engineering. 
          
          - Multi-Site IT management experience
          - DevOps (AWS, Docker, VPS platforms)
          - Large Scale Cloud Platform deployments and management
          - Database Management (MSSQL, PostgreSQL, MySQL, Redis)
          - Project Management
          - Vendor management & contract negotiations
          
          FinTech experience including Bitcoin (BTC), Ethereum (ETH), and other cryptocurrencies. Experience with Blockchain and Bitcoin 2.0 development.
          
          Specialties include: Strategic Planning & Decision Making, Executive Leadership & Supervision, Web DevOps, programming, Technical Infrastructure, Big Data, Customer Service Delivery, AWS platform, VoIP, Disaster Recovery, Emergency Response Plans, Policy Development, Project Management Systems, Development of Business Plans.
          """

    # Reference section
    [params.reference]
        enable = true
        icon = "fa-pencil"
        title = "Reference"
        summary = """
        **Reference for Adam Brown**
        
        To whom it may concern: 
        
        This is a letter of recommendation for Adam Brown. Adam worked for Payment Approved for the inception of a new payment processing platform. Adam was instrumental in helping with a full discovery process through development sprints. During this time Adam grew as a professional and his creativity solved may questions. If any parties have any questions in regards Adams past work experience at Payment Approved, please contact me directly via email.
        
        Thank you,
        
        Jason Montoya, CEO
        """


    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Work"

        [[params.jobs.list]]
        position = "Applications Programmer III"
        dates = "Jan 2019 - Nov 2021"
        company = "Cornell University - College of Engineering / CIS IT Service Group"
        details = ""



    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**A list of side projects** (in chronological order)"

        [[params.projects.list]]
        title = "Strodes College Physics bridge building competition"
        url = "/assets/images/strodes-bridge-building-competition-original.png"
        tagline = "Our team were awarded first prize at St. James’ Palace by the Duke of Edinburgh. “Nine of the college’s physicists won a bridge-building competition organised by the Science and Technology Research Organisation (SATRO). Working in a Physics lab in their spare time, Andrew Potter, Thomas Hayes, Nick Woods, Jan Nyeki, Maria Nyekiova, and Rob Evans designed, built and tested a bridge from glass fibre.” Press photo; August 2nd 2002;"
        screenshot = "strodes-bridge-building-competition.png"

        [[params.projects.list]]
        title = "Wave Simulation software using the wave speed equation"
        url = "https://www.youtube.com/watch?v=XoGHKp3PiHQ"
        tagline = "Written in C++ using OpenGL 1.1. Compiled using Visual C++ on Windows and GNU GCC on Gentoo Linux. Programmed by Andrew Potter 2002."
        screenshot = "strodes-wave-simulation-app.png"

        [[params.projects.list]]
        title = "Yateley School Map 3d"
        url = "/assets/images/yateley-school-map-original.gif"
        tagline = "Programmed by Andrew Potter in 2017. Using Blender 3d and Blend4Web with Ruby on Rails and CoffeeScript."
        screenshot = "yateley-school-map.gif"

        [[params.projects.list]]
        title = "QALB P2P platform"
        url = "/assets/images/QALB_20220107-2022-01-10_12.23.26.gif"
        tagline = "QALB is a reference to the heart. QALB is scaffolding for your community, including an e-learning platform which will come loaded with educational content. After a decade of research and development this is now being actively developed."
        screenshot = "QALB_20220107-2022-01-10_12.23.26_small.gif"

    # Skills section
    [params.skills]
        enable = false
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Linux"
        level = "80%"

        [[params.skills.list]]
        skill = "Elixir/Phoenix"
        level = "30%"

        [[params.skills.list]]
        skill = "Ruby on Rails"
        level = "70%"

        [[params.skills.list]]
        skill = "Ethical hacking"
        level = "30%"

        [[params.skills.list]]
        skill = "AI/Machine Learning"
        level = "20%"

        [[params.skills.list]]
        skill = "Blockchain/Solidity"
        level = "30%"

        [[params.skills.list]]
        skill = "Blender CGI/VFX"
        level = "15%"


    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Adam Brown"
